---
- hosts: all
  tasks:
    - name: ping
      ping:

    - name: create test file
      file:
        path: ~/healthcheck
        state: touch

    - name: Create new user
      become: yes
      user:
        append: yes
        name: "smth"
        groups: sudo
        generate_ssh_key: yes
