---
- hosts: vagrant_vm
  tasks:
    - name: ping
      ping:
    - name: create test file
      file:
        path: ~/healthcheck
        state: touch
    - name: become!
      become: yes
      package:
        name: joe
        state: present
        
